# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f446a04e23796fdc22a1268e58a1c46187d3d348fe7495e700b8f2bbcfbe6ced07a872341313463b8185f98a3f006f34078f708d47a621f0f2147da1f7c94705

test:
  secret_key_base: 343d47e6b1aaf92e3624d6cee16a121a3a29eac069b6b519fc9376e3e7a95fba4527889f0bb1e4bfcf43e80c8be81a5db35c0a0162a095481ca222c91419a147

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
